Gcpoauth
splunk/security-content pull request #665
Opened 2020-09-09 16:22 UTC by rosplk

gcp oauth abuse detection search

2020-09-14 19:27 UTC, philroyer-phantom commented on stories/gcp_cross_account_activity.yml
> +description: Track when a user assumes an IAM role in another AWS account to obtain
Should this be "GCP" instead of "AWS"?

2020-09-14 19:37 UTC, rosplk commented on stories/gcp_cross_account_activity.yml
> +description: Track when a user assumes an IAM role in another AWS account to obtain
This is a story it was fixed to be GCP

2020-09-14 20:12 UTC, patel-bhavin requested changes

2020-09-14 20:12 UTC, patel-bhavin commented on detections/gcp_detect_oauth_token_abuse.yml
> +search: '`sourcetype=google:gcp:pubsub:message type.googleapis.com/google.cloud.audit.AuditLog |table protoPayload.@type protoPayload.status.details{}.@type protoPayload.status.details{}.violations{}
the last macro needs "_filter"
the sourcetype in the beginning should be a macro

2020-09-14 20:12 UTC, patel-bhavin commented on detections/gcp_detect_oauth_token_abuse.yml
> +    - "GCP Cross Account Activity"
updated the formating in the yml

2020-09-14 20:12 UTC, patel-bhavin commented on stories/gcp_cross_account_activity.yml
> +  analytics_story: GCP Cross Account Activity
we have to add this story to atleast one response task for generate.py to run

2020-09-17 17:48 UTC, patel-bhavin approved these changes

2020-09-17 17:48 UTC, merged